// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: Admin.proto

package admin_service

import (
	context "context"
	base_service "github.com/b1gdea1/checkin_client/base_service"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//更新问题
type QuestionUpdateResult int32

const (
	QuestionUpdateResult_QUESTION_UPDATE_SUCCESS    QuestionUpdateResult = 0
	QuestionUpdateResult_QUESTION_UPDATE_NO_LOGIN   QuestionUpdateResult = 1
	QuestionUpdateResult_QUESTION_UPDATE_NO_ADMIN   QuestionUpdateResult = 2
	QuestionUpdateResult_QUESTION_UPDATE_ILLEGAL    QuestionUpdateResult = 3
	QuestionUpdateResult_QUESTION_UPDATE_TOKEN_FAIL QuestionUpdateResult = 4
)

// Enum value maps for QuestionUpdateResult.
var (
	QuestionUpdateResult_name = map[int32]string{
		0: "QUESTION_UPDATE_SUCCESS",
		1: "QUESTION_UPDATE_NO_LOGIN",
		2: "QUESTION_UPDATE_NO_ADMIN",
		3: "QUESTION_UPDATE_ILLEGAL",
		4: "QUESTION_UPDATE_TOKEN_FAIL",
	}
	QuestionUpdateResult_value = map[string]int32{
		"QUESTION_UPDATE_SUCCESS":    0,
		"QUESTION_UPDATE_NO_LOGIN":   1,
		"QUESTION_UPDATE_NO_ADMIN":   2,
		"QUESTION_UPDATE_ILLEGAL":    3,
		"QUESTION_UPDATE_TOKEN_FAIL": 4,
	}
)

func (x QuestionUpdateResult) Enum() *QuestionUpdateResult {
	p := new(QuestionUpdateResult)
	*p = x
	return p
}

func (x QuestionUpdateResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionUpdateResult) Descriptor() protoreflect.EnumDescriptor {
	return file_Admin_proto_enumTypes[0].Descriptor()
}

func (QuestionUpdateResult) Type() protoreflect.EnumType {
	return &file_Admin_proto_enumTypes[0]
}

func (x QuestionUpdateResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionUpdateResult.Descriptor instead.
func (QuestionUpdateResult) EnumDescriptor() ([]byte, []int) {
	return file_Admin_proto_rawDescGZIP(), []int{0}
}

//发布通知
type NoticeResult int32

const (
	NoticeResult_NOTICE_SEND_SUCCESS         NoticeResult = 0
	NoticeResult_NOTICE_USER_DOSE_NOT_EXIST  NoticeResult = 1
	NoticeResult_NOTICE_ADMIN_DOSE_NOT_EXIST NoticeResult = 2
	NoticeResult_NOTICE_ADMIN_DOST_NOT_LOGIN NoticeResult = 3
	NoticeResult_NOTICE_SEND_FAIL            NoticeResult = 4
)

// Enum value maps for NoticeResult.
var (
	NoticeResult_name = map[int32]string{
		0: "NOTICE_SEND_SUCCESS",
		1: "NOTICE_USER_DOSE_NOT_EXIST",
		2: "NOTICE_ADMIN_DOSE_NOT_EXIST",
		3: "NOTICE_ADMIN_DOST_NOT_LOGIN",
		4: "NOTICE_SEND_FAIL",
	}
	NoticeResult_value = map[string]int32{
		"NOTICE_SEND_SUCCESS":         0,
		"NOTICE_USER_DOSE_NOT_EXIST":  1,
		"NOTICE_ADMIN_DOSE_NOT_EXIST": 2,
		"NOTICE_ADMIN_DOST_NOT_LOGIN": 3,
		"NOTICE_SEND_FAIL":            4,
	}
)

func (x NoticeResult) Enum() *NoticeResult {
	p := new(NoticeResult)
	*p = x
	return p
}

func (x NoticeResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoticeResult) Descriptor() protoreflect.EnumDescriptor {
	return file_Admin_proto_enumTypes[1].Descriptor()
}

func (NoticeResult) Type() protoreflect.EnumType {
	return &file_Admin_proto_enumTypes[1]
}

func (x NoticeResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NoticeResult.Descriptor instead.
func (NoticeResult) EnumDescriptor() ([]byte, []int) {
	return file_Admin_proto_rawDescGZIP(), []int{1}
}

type QuestionUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminId   string                   `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Token     string                   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Questions []*base_service.Question `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *QuestionUpdateRequest) Reset() {
	*x = QuestionUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionUpdateRequest) ProtoMessage() {}

func (x *QuestionUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionUpdateRequest.ProtoReflect.Descriptor instead.
func (*QuestionUpdateRequest) Descriptor() ([]byte, []int) {
	return file_Admin_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionUpdateRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *QuestionUpdateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *QuestionUpdateRequest) GetQuestions() []*base_service.Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type QuestionUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string               `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Result QuestionUpdateResult `protobuf:"varint,2,opt,name=result,proto3,enum=proto.QuestionUpdateResult" json:"result,omitempty"`
}

func (x *QuestionUpdateResponse) Reset() {
	*x = QuestionUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionUpdateResponse) ProtoMessage() {}

func (x *QuestionUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionUpdateResponse.ProtoReflect.Descriptor instead.
func (*QuestionUpdateResponse) Descriptor() ([]byte, []int) {
	return file_Admin_proto_rawDescGZIP(), []int{1}
}

func (x *QuestionUpdateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *QuestionUpdateResponse) GetResult() QuestionUpdateResult {
	if x != nil {
		return x.Result
	}
	return QuestionUpdateResult_QUESTION_UPDATE_SUCCESS
}

type NoticeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID     string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Msg        string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	AdminID    string `protobuf:"bytes,3,opt,name=AdminID,proto3" json:"AdminID,omitempty"`
	AdminToken string `protobuf:"bytes,4,opt,name=AdminToken,proto3" json:"AdminToken,omitempty"`
	TTL        int32  `protobuf:"varint,5,opt,name=TTL,proto3" json:"TTL,omitempty"`
}

func (x *NoticeRequest) Reset() {
	*x = NoticeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeRequest) ProtoMessage() {}

func (x *NoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeRequest.ProtoReflect.Descriptor instead.
func (*NoticeRequest) Descriptor() ([]byte, []int) {
	return file_Admin_proto_rawDescGZIP(), []int{2}
}

func (x *NoticeRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *NoticeRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NoticeRequest) GetAdminID() string {
	if x != nil {
		return x.AdminID
	}
	return ""
}

func (x *NoticeRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *NoticeRequest) GetTTL() int32 {
	if x != nil {
		return x.TTL
	}
	return 0
}

type NoticeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result NoticeResult `protobuf:"varint,1,opt,name=Result,proto3,enum=proto.NoticeResult" json:"Result,omitempty"`
}

func (x *NoticeResp) Reset() {
	*x = NoticeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Admin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeResp) ProtoMessage() {}

func (x *NoticeResp) ProtoReflect() protoreflect.Message {
	mi := &file_Admin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeResp.ProtoReflect.Descriptor instead.
func (*NoticeResp) Descriptor() ([]byte, []int) {
	return file_Admin_proto_rawDescGZIP(), []int{3}
}

func (x *NoticeResp) GetResult() NoticeResult {
	if x != nil {
		return x.Result
	}
	return NoticeResult_NOTICE_SEND_SUCCESS
}

var File_Admin_proto protoreflect.FileDescriptor

var file_Admin_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2d,
	0x0a, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x63, 0x0a,
	0x16, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x33, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x54, 0x4c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x54, 0x54, 0x4c, 0x22, 0x39, 0x0a, 0x0a, 0x4e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0xac, 0x01, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b,
	0x0a, 0x17, 0x51, 0x55, 0x45, 0x53, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x51,
	0x55, 0x45, 0x53, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x4e,
	0x4f, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x4e, 0x4f, 0x5f,
	0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x49, 0x4c, 0x4c, 0x45, 0x47,
	0x41, 0x4c, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x51, 0x55, 0x45, 0x53, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x10, 0x04, 0x2a, 0x9f, 0x01, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17, 0x0a, 0x13, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x5f,
	0x53, 0x45, 0x4e, 0x44, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x1e,
	0x0a, 0x1a, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x44, 0x4f,
	0x53, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0x01, 0x12, 0x1f,
	0x0a, 0x1b, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x44,
	0x4f, 0x53, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0x02, 0x12,
	0x1f, 0x0a, 0x1b, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f,
	0x44, 0x4f, 0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x03,
	0x12, 0x14, 0x0a, 0x10, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x5f,
	0x46, 0x41, 0x49, 0x4c, 0x10, 0x04, 0x32, 0x98, 0x01, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x4e, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x62, 0x31, 0x67, 0x64, 0x65, 0x61, 0x31, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x5f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Admin_proto_rawDescOnce sync.Once
	file_Admin_proto_rawDescData = file_Admin_proto_rawDesc
)

func file_Admin_proto_rawDescGZIP() []byte {
	file_Admin_proto_rawDescOnce.Do(func() {
		file_Admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_Admin_proto_rawDescData)
	})
	return file_Admin_proto_rawDescData
}

var file_Admin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Admin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Admin_proto_goTypes = []interface{}{
	(QuestionUpdateResult)(0),      // 0: proto.QuestionUpdateResult
	(NoticeResult)(0),              // 1: proto.NoticeResult
	(*QuestionUpdateRequest)(nil),  // 2: proto.QuestionUpdateRequest
	(*QuestionUpdateResponse)(nil), // 3: proto.QuestionUpdateResponse
	(*NoticeRequest)(nil),          // 4: proto.NoticeRequest
	(*NoticeResp)(nil),             // 5: proto.NoticeResp
	(*base_service.Question)(nil),  // 6: proto.Question
}
var file_Admin_proto_depIdxs = []int32{
	6, // 0: proto.QuestionUpdateRequest.questions:type_name -> proto.Question
	0, // 1: proto.QuestionUpdateResponse.result:type_name -> proto.QuestionUpdateResult
	1, // 2: proto.NoticeResp.Result:type_name -> proto.NoticeResult
	4, // 3: proto.AdminService.PublishNotice:input_type -> proto.NoticeRequest
	2, // 4: proto.AdminService.UpdateQuestions:input_type -> proto.QuestionUpdateRequest
	5, // 5: proto.AdminService.PublishNotice:output_type -> proto.NoticeResp
	3, // 6: proto.AdminService.UpdateQuestions:output_type -> proto.QuestionUpdateResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Admin_proto_init() }
func file_Admin_proto_init() {
	if File_Admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestionUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestionUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Admin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Admin_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Admin_proto_goTypes,
		DependencyIndexes: file_Admin_proto_depIdxs,
		EnumInfos:         file_Admin_proto_enumTypes,
		MessageInfos:      file_Admin_proto_msgTypes,
	}.Build()
	File_Admin_proto = out.File
	file_Admin_proto_rawDesc = nil
	file_Admin_proto_goTypes = nil
	file_Admin_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	PublishNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeResp, error)
	UpdateQuestions(ctx context.Context, in *QuestionUpdateRequest, opts ...grpc.CallOption) (*QuestionUpdateResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) PublishNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeResp, error) {
	out := new(NoticeResp)
	err := c.cc.Invoke(ctx, "/proto.AdminService/PublishNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateQuestions(ctx context.Context, in *QuestionUpdateRequest, opts ...grpc.CallOption) (*QuestionUpdateResponse, error) {
	out := new(QuestionUpdateResponse)
	err := c.cc.Invoke(ctx, "/proto.AdminService/UpdateQuestions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	PublishNotice(context.Context, *NoticeRequest) (*NoticeResp, error)
	UpdateQuestions(context.Context, *QuestionUpdateRequest) (*QuestionUpdateResponse, error)
}

// UnimplementedAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (*UnimplementedAdminServiceServer) PublishNotice(context.Context, *NoticeRequest) (*NoticeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishNotice not implemented")
}
func (*UnimplementedAdminServiceServer) UpdateQuestions(context.Context, *QuestionUpdateRequest) (*QuestionUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQuestions not implemented")
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_PublishNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PublishNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AdminService/PublishNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PublishNotice(ctx, req.(*NoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AdminService/UpdateQuestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateQuestions(ctx, req.(*QuestionUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishNotice",
			Handler:    _AdminService_PublishNotice_Handler,
		},
		{
			MethodName: "UpdateQuestions",
			Handler:    _AdminService_UpdateQuestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Admin.proto",
}
